// <auto-generated />
using System;
using Fakeflix.Membership.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fakeflix.Membership.Database.Migrations
{
    [DbContext(typeof(LabbFakeflixContext))]
    [Migration("20230206133703_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fakeflix.Membership.Database.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chloé Zhao"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ava DuVernay"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kathryn Bigelow"
                        });
                });

            modelBuilder.Entity("Fakeflix.Membership.Database.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<string>("FilmUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("Free")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Released")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum",
                            DirectorId = 1,
                            FilmUrl = "https://www.youtube.com/watch?v=yFQyrYSvqPI",
                            Free = true,
                            Released = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wonder Woman"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum",
                            DirectorId = 1,
                            FilmUrl = "https://www.youtube.com/watch?v=IkOK8tdEsFY",
                            Free = true,
                            Released = new DateTime(2021, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Hulk"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum",
                            DirectorId = 2,
                            FilmUrl = "https://www.youtube.com/watch?v=DKP16d_WdZM",
                            Free = true,
                            Released = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cat Woman"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lorem ipsum",
                            DirectorId = 2,
                            FilmUrl = "https://www.youtube.com/watch?v=CsGYh8AacgY",
                            Free = true,
                            Released = new DateTime(2019, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter and the Sorcerers Stone"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lorem ipsum",
                            DirectorId = 3,
                            FilmUrl = "https://www.youtube.com/watch?v=jNQXAC9IVRw",
                            Free = true,
                            Released = new DateTime(2012, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter and the Goblet of Fire"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lorem ipsum",
                            DirectorId = 3,
                            FilmUrl = "https://www.youtube.com/watch?v=QH2-TGUlwu4",
                            Free = true,
                            Released = new DateTime(2018, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars : A New Hope"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lorem ipsum",
                            DirectorId = 3,
                            FilmUrl = "https://www.youtube.com/watch?v=e_04ZrNroTo",
                            Free = true,
                            Released = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Force Awakens"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Lorem ipsum",
                            DirectorId = 1,
                            FilmUrl = "https://www.youtube.com/watch?v=L0MK7qz13bU",
                            Free = true,
                            Released = new DateTime(2002, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Last Jedi"
                        });
                });

            modelBuilder.Entity("Fakeflix.Membership.Database.Entities.FilmGenre", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("FilmId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("FilmGenres", (string)null);

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            FilmId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            FilmId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            FilmId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            FilmId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            FilmId = 4,
                            GenreId = 3
                        },
                        new
                        {
                            FilmId = 5,
                            GenreId = 3
                        },
                        new
                        {
                            FilmId = 6,
                            GenreId = 2
                        },
                        new
                        {
                            FilmId = 7,
                            GenreId = 2
                        },
                        new
                        {
                            FilmId = 8,
                            GenreId = 2
                        });
                });

            modelBuilder.Entity("Fakeflix.Membership.Database.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fantasy"
                        });
                });

            modelBuilder.Entity("Fakeflix.Membership.Database.Entities.SimilarFilms", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("SimilarFilmId")
                        .HasColumnType("int");

                    b.HasKey("FilmId", "SimilarFilmId");

                    b.HasIndex("SimilarFilmId");

                    b.ToTable("SimilarFilms");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            SimilarFilmId = 2
                        },
                        new
                        {
                            FilmId = 1,
                            SimilarFilmId = 3
                        },
                        new
                        {
                            FilmId = 2,
                            SimilarFilmId = 1
                        },
                        new
                        {
                            FilmId = 2,
                            SimilarFilmId = 3
                        },
                        new
                        {
                            FilmId = 4,
                            SimilarFilmId = 5
                        },
                        new
                        {
                            FilmId = 5,
                            SimilarFilmId = 4
                        },
                        new
                        {
                            FilmId = 6,
                            SimilarFilmId = 7
                        },
                        new
                        {
                            FilmId = 6,
                            SimilarFilmId = 8
                        },
                        new
                        {
                            FilmId = 7,
                            SimilarFilmId = 6
                        },
                        new
                        {
                            FilmId = 7,
                            SimilarFilmId = 8
                        },
                        new
                        {
                            FilmId = 8,
                            SimilarFilmId = 6
                        },
                        new
                        {
                            FilmId = 8,
                            SimilarFilmId = 7
                        });
                });

            modelBuilder.Entity("Fakeflix.Membership.Database.Entities.Film", b =>
                {
                    b.HasOne("Fakeflix.Membership.Database.Entities.Director", "Director")
                        .WithMany("Films")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("Fakeflix.Membership.Database.Entities.FilmGenre", b =>
                {
                    b.HasOne("Fakeflix.Membership.Database.Entities.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fakeflix.Membership.Database.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Fakeflix.Membership.Database.Entities.SimilarFilms", b =>
                {
                    b.HasOne("Fakeflix.Membership.Database.Entities.Film", "Film")
                        .WithMany("SimilarFilms")
                        .HasForeignKey("FilmId")
                        .IsRequired();

                    b.HasOne("Fakeflix.Membership.Database.Entities.Film", "Similar")
                        .WithMany()
                        .HasForeignKey("SimilarFilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Similar");
                });

            modelBuilder.Entity("Fakeflix.Membership.Database.Entities.Director", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("Fakeflix.Membership.Database.Entities.Film", b =>
                {
                    b.Navigation("SimilarFilms");
                });
#pragma warning restore 612, 618
        }
    }
}
